version: '3.9'
services:
  web:
    build: .
    container_name: victoria_web
    environment:
      - NODE_ENV=production
    expose:
      - "3000"
    restart: unless-stopped

  caddy:
    image: caddy:2.8.4-alpine
    container_name: victoria_caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - web
    restart: unless-stopped

volumes:
  caddy_data: {}
  caddy_config: {}
